api/urls.py
from django.urls import path
from . views import UploadAPIView, SharedAPIView, DetailShare, DetailUpload

urlpatterns = [

path('upload', UploadAPIView.as_view(), name="uploadapi"),
path('upload/<int:pk>/', DetailUpload.as_view(), name="detail_uploadapi"),
path('share', SharedAPIView.as_view(), name="sharedapi"),
path('share/<int:pk>/', DetailShare.as_view(), name="detail_sharedapi"),

]

merga_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('merge_app.urls'), name='merga_home'),
    path('api/', include('api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merge_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'merge'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('user', views.dashboard, name='dashboard'),
    path('share/<int:obj_id>', views.change_status, name='share'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),\
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),\
        name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),\
        name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),\
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),\
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),\
        name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('<pk>/delete', views.DeleteFile.as_view(), name='delete'),
    path('upload/', views.upload, name='upload'),
    path('edit/<int:obj_id>/', views.editForm, name='edit'),

]

merge_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

#Model to upload file
class UploadFile(models.Model):
    STATUS_CHOICES = (
        ('private', 'Private'),
        ('share_all', 'Share publicly'),
        ('share_friends', 'Share with friends')
    )
    user =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_upload')
    record_no = models.CharField(max_length=30)
    file_name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    document = models.FileField(upload_to='uploads/%Y/%m/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    share_status = models.CharField(max_length=13, choices=STATUS_CHOICES,\
        default='private')

    class Meta:
        ordering = ('-uploaded_at',)

    
    def __str__(self):
        return self.document.url
    

    

class SharedFile(models.Model):
    share_by = models.ForeignKey(User, on_delete=models.CASCADE,\
        related_name='user_shared')
    file_id = models.ForeignKey(UploadFile, on_delete=models.CASCADE,\
        related_name='shared_file')

    #class Meta:
        #ordering = ('-file_id__uploaded_at',)
        # i used the order_by(file_id____uploaded_at) in the view


    def __str__(self):
        return self.file_id.file_name

merge_app/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import SharedFile, UploadFile
from django.forms.widgets import Textarea


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        
        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']




class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ('document', 'record_no', 'file_name', 'description', 'share_status')
        widgets = {
            'description': Textarea()
        }



class Shareform(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ('share_status',)



class Upload_EditForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = fields = ('record_no', 'file_name', 'description', 'share_status')
        widgets = {
            'description': Textarea()
        }

merge_app/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm
from .models import UploadFile, SharedFile
from django.contrib.auth.models import User
from . forms import UploadForm, Shareform, Upload_EditForm
from django.views.generic.edit import DeleteView
from django.core.exceptions import PermissionDenied


# Create your views here.

@login_required
def home_page(request):
    obj = SharedFile.objects.filter(file_id__share_status='share_all').order_by('-file_id__uploaded_at',)
    #to access related field we must use double __   e.g __share_status
    context = {'obj':obj}
    return render(request, 'merge_app/home.html', context)



@login_required
def dashboard(request):
    this_user = User.objects.get(pk=request.user.id)
    if(request.user == this_user):
        try:
            current_user_object = UploadFile.objects.all().filter(user=request.user.id)
        except UploadFile.DoesNotExist:
            current_user_object = "No file uploaded yet"
        context = {'current_user_object': current_user_object, 'this_user': this_user}
        return render(request, 'merge_app/dashboard.html', context)

    raise PermissionDenied()



def register(request):
    if(request.method == 'POST'):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
        # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
        # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
        # Save the User object
            new_user.save()
            return render(request, 'merge_app/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'merge_app/register.html', {'user_form': user_form})


class DeleteFile(DeleteView):
    model = UploadFile
    
    success_url = "/"




@login_required
def change_status(request, obj_id):
    this_user = User.objects.get(pk=request.user.id)
    if(this_user == request.user):
        if(request.method == 'POST'):
            update_form = Shareform(request.POST)
            if(update_form.is_valid()):
                data = update_form.cleaned_data['share_status']
                UploadFile.objects.filter(pk = obj_id).update(share_status=data)
                obj = SharedFile.objects.filter(file_id__share_status='share_all').order_by('-file_id__uploaded_at',)
                context = {'obj':obj}
                return render(request, 'merge_app/home.html', context)

    update_form = Shareform()
    context = {'update_form':update_form}
    return render(request, 'merge_app/status.html', context)

        



@login_required
def upload(request):
    this_user = User.objects.get(pk=request.user.id)
    if(request.user == this_user):
        new_upload = None
        new_share = None
        if(request.method == 'POST'):
            upload_form = UploadForm(request.POST, request.FILES)
            if(upload_form.is_valid()):
                new_upload = upload_form.save(commit=False)
                new_upload.user = this_user
                new_upload.save()
                new_share = SharedFile.objects.create(share_by=this_user, file_id=new_upload)
                new_share.save()
                messages.success(request, f'Succesfully Uploaded {new_upload.file_name}')
                upload_form = UploadForm()
                current_user_object = UploadFile.objects.all().filter(user=request.user.id)
                context = {'current_user_object':current_user_object}
                return render(request, 'merge_app/dashboard.html', context)
        else:
            upload_form = UploadForm()
        

    context = {'upload_form': upload_form, 'this_user': this_user}
    return render(request, 'merge_app/upload.html', context)


    
@login_required
def editForm(request, obj_id):
    this_user = User.objects.get(pk=request.user.id)
    if(this_user == request.user):
        obj_to_update = UploadFile.objects.get(pk=obj_id)
        if(request.user == this_user):
            if(request.method == 'POST'):
                updated_form = Upload_EditForm(request.POST, instance=obj_to_update)
                if(updated_form.is_valid()):
                    updated_form.user = this_user
                    updated_form.save()
                    messages.success(request, f'Succesfully Updated {obj_to_update.file_name}')
            
            updated_form = Upload_EditForm(instance=obj_to_update)
            context = {'updated_form': updated_form}
            return render(request, 'merge_app/edit.html', context)
    raise PermissionDenied()

merge_app/templates/merge_app/all.html
{% extends "merge_app/base.html" %}

{% block title %}All Posts{% endblock %}

{% block content %}
    {% for item in obj %}
        <p><img src="{{ item.document.url }}" alt="{{ item.file_name }}"></p>
    {% endfor %}
{% endblock content %}

merge_app/templates/merge_app/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
      <title>{% block title %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="{% static "css/main.css" %}?{% now "U" %}" rel="stylesheet">
    </head>

<body>
    <div id="header">
        <div><a href="{% url "merge:home" %}"<span class="logo">Merga Yazilim</span></a></div>
        {% if request.user.is_authenticated %}
            <div>
                <ul class="menu">
                    <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "merge:dashboard" %}">My dashboard</a>
                    </li>
                    
                    <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url "merge:upload" %}">Upload</a>
                    </li>

                    <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="#">People</a>
                    </li>
                </ul>
            </div>
                
        {% endif %}
        
        <div>
            <span class="user">
                {% if request.user.is_authenticated %}
                    <p>Hello {{ request.user.username }} <a href="{% url "merge:logout" %}">Logout</a></p>
                {% else %}
                    <a href="{% url "merge:login" %}">Log-in</a>
                {% endif %}
            </span>
        </div>
    </div>
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

merge_app/templates/merge_app/dashboard.html
{% extends "merge_app/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="dash-div">
    <h1>Dashboard</h1>
    <p>Welcome to your dashboard.</p>
</div>

<div class="posted-div">
    {% for item in current_user_object %}
        <div>
            <p><img src="{{ item.document.url }}" alt="{{ item.file_name }}"></p>
            <p><a href="{% url "merge:share" item.id %}"><button type='submit'>Share<button></a></p>
            <p><a href="{% url "merge:delete" item.id %}"><button type='submit'>Delete<button></a></p>
            <p><a href="{% url "merge:edit" item.id %}"><button type='submit'>Edit<button></a></p>
        </div>
    {% endfor %}
</div>

{% endblock content %}

merge_app/templates/merge_app/edit.html
{% extends "merge_app/base.html" %}

{% block title %}Upload file{% endblock %}

{% block content %}
<div class="form-div">
    <h1>Edit Details</h1>
    <form action='' method='post'>
        {% csrf_token %}
        {{ updated_form.as_p }}
        <input type='submit' value='Change'>
    </form>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
         <li {% if message.tags %} class="{{ message.tag }}" {% endif %}>
            {{ message }}
        </li>
        {% endfor %}
        </ul>
        {% endif %}
</div>
{% endblock content %}

merge_app/templates/merge_app/home.html
{% extends "merge_app/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="posted-div">
    {% for item in obj %}
    <div class="home-items">
        <h1>Shared by {{ item.share_by }}</h1>
        <p><img src="{{ item.file_id }}"></p>
    </div>
    {% endfor %}
{% endblock content %}

merge_app/templates/merge_app/register.html
{% extends "merge_app/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}

<h1>Create an account</h1>

<p>Please, sign up using the following form:</p>

<form method="post">

{{ user_form.as_p }}

{% csrf_token %}

<p><input type="submit" value="Create my account"></p>

</form>

{% endblock %}

merge_app/templates/merge_app/register_done.html
{% extends "merge_app/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}

<h1>Welcome {{ new_user.first_name }}!</h1>

<p>Your account has been successfully created. Now you can <a

href="{% url "merge:login" %}">log in</a>.</p>

{% endblock %}

merge_app/templates/merge_app/status.html
{% extends "merge_app/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        {{ update_form.as_p }}
        <input type='submit' value='Change status'>
    </form>
{% endblock content %}

merge_app/templates/merge_app/upload.html
{% extends "merge_app/base.html" %}

{% block title %}Upload file{% endblock %}

{% block content %}
<div class="form-div">
    <h1>Upload your Document</h1>
    <form action='' method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ upload_form.as_p }}
        <input type='submit' value='Upload'>
    </form>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
         <li {% if message.tags %} class="{{ message.tag }}" {% endif %}>
            {{ message }}
        </li>
        {% endfor %}
        </ul>
        {% endif %}
</div>
<script type="text/javascript">
    setTimeout(funtion() {
        window.location.href="/dashboard/";
    },2000);
</script>
{% endblock content %}

merge_app/templates/merge_app/uploadfile_confirm_delete.html
<form method='post'>
{% csrf_token %}
<p>are you sure you want to delete {{ uploadfile.file_name }}
<input type='submit' value='Confirm'>
</form>